// Code generated by protoc-gen-go.
// source: grpc.proto
// DO NOT EDIT!

/*
Package nlu_grpc is a generated protocol buffer package.

It is generated from these files:
	grpc.proto

It has these top-level messages:
	NluRequest
	NluReply
*/
package nlu_grpc

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// The request message containing the user's name.
type NluRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *NluRequest) Reset()         { *m = NluRequest{} }
func (m *NluRequest) String() string { return proto.CompactTextString(m) }
func (*NluRequest) ProtoMessage()    {}

// The response message containing the greetings
type NluReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *NluReply) Reset()         { *m = NluReply{} }
func (m *NluReply) String() string { return proto.CompactTextString(m) }
func (*NluReply) ProtoMessage()    {}
